### Do not edit -- Generated by 'configure --with-whatever' from Makefile.in
### STK examples Makefile - for various flavors of unix

PROGRAMS = voder_ex
RM = /bin/rm
SRC_PATH = src
OBJECT_PATH = Release
vpath %.o $(OBJECT_PATH)

INCLUDE = src/include
ifeq ($(strip $(INCLUDE)), )
	INCLUDE = include
endif
vpath %.h $(INCLUDE)

CC       = g++
DEFS     =   -DHAVE_GETTIMEOFDAY -D__LINUX_ALSA__
DEFS    += -D__LITTLE_ENDIAN__
CFLAGS   = -O3 -Wall
CFLAGS  += -I$(INCLUDE) -I$(INCLUDE)
LIBRARY = -lpthread -lasound -lm 

REALTIME = yes
ifeq ($(REALTIME),yes)
  
endif

%.o : $(SRC_PATH)/%.cpp $(OBJECT_PATH)/.placeholder
	$(CC) $(CFLAGS) $(DEFS) -c $(<) -o $(OBJECT_PATH)/$@

%.o : include/%.cpp $(OBJECT_PATH)/.placeholder
	$(CC) $(CFLAGS) $(DEFS) -c $(<) -o $(OBJECT_PATH)/$@

all : $(PROGRAMS)

$(OBJECT_PATH)/.placeholder:
	mkdir -vp $(OBJECT_PATH)
	touch $(OBJECT_PATH)/.placeholder

$(OBJECTS) : Stk.h

clean : 
	$(RM) -f $(OBJECT_PATH)/*.o
	$(RM) -f $(PROGRAMS) *.exe
	$(RM) -fR *~ *.dSYM

distclean: clean
	$(RM) Makefile

voder_ex: Voder_example.cpp Stk.o BlitSaw.o Noise.o RtAudio.o FormSwep.o
		$(CC) $(LDFLAGS) $(CFLAGS) $(DEFS) -o example Voder_example.cpp $(OBJECT_PATH)/Stk.o $(OBJECT_PATH)/BlitSaw.o $(OBJECT_PATH)/Noise.o $(OBJECT_PATH)/RtAudio.o $(OBJECT_PATH)/FormSwep.o $(LIBRARY)
